# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x07metrics\"L\n\x16LocationMetricsRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\"*\n\x17LocationMetricsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32j\n\x0eMetricsService\x12X\n\x13SaveLocationMetrics\x12\x1f.metrics.LocationMetricsRequest\x1a .metrics.LocationMetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCATIONMETRICSREQUEST']._serialized_start=26
  _globals['_LOCATIONMETRICSREQUEST']._serialized_end=102
  _globals['_LOCATIONMETRICSRESPONSE']._serialized_start=104
  _globals['_LOCATIONMETRICSRESPONSE']._serialized_end=146
  _globals['_METRICSSERVICE']._serialized_start=148
  _globals['_METRICSSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
